test

diff --git a/.github/workflows/gitleaks.yaml b/.github/workflows/gitleaks.yaml
--- a/.github/workflows/gitleaks.yaml
+++ b/.github/workflows/gitleaks.yaml
@@ -4,18 +4,39 @@ jobs:
   scan:
     name: gitleaks
     runs-on: ubuntu-latest
-    container: #起動するコンテナイメージを指定
-      image: ghcr.io/gitleaks/gitleaks:latest #指定のdockerイメージを使用
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Run Gitleaks scan
+        uses: docker://ghcr.io/gitleaks/gitleaks:latest
         with:
-          fetch-depth: 0
-      - run: |
-          gitleaks detect
-      # - uses: gitleaks/gitleaks-action@v2
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
-      # - uses: stoplightio/spectral-action@latest
-      #   with:
-      #     file_glob: "apimartifacts/apis/**/*.json"
+          args: detect -v -r gitleaks-report.json
+
+      - name: Upload Gitleaks report
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: gitleaks-report
+          path: gitleaks-report.json
+
+      - name: Fail on leaks
+        if: failure()
+        run: |
+          echo "Gitleaks detected leaks, failing the job."
+          exit 1
+    # container: #起動するコンテナイメージを指定
+    #   image: ghcr.io/gitleaks/gitleaks:latest #指定のdockerイメージを使用
+    # steps:
+    #   - uses: actions/checkout@v3
+    #     with:
+    #       fetch-depth: 0
+    #   - run: |
+    #       gitleaks detect
+    # - uses: gitleaks/gitleaks-action@v2
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
+    # - uses: stoplightio/spectral-action@latest
+    #   with:
+    #     file_glob: "apimartifacts/apis/**/*.json"
